version: "3"
services:
    nginx:
        build:
            context: .
            dockerfile: dockerfiles/nginx/Dockerfile
        ports:
            - "8080:80"
        networks:
            - internal
        volumes:
            - ./data/:/var/www/html/
            - ./logs/nginx:/var/log/nginx/
    php:
        container_name: animal-generator-php
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        networks:
            - internal
        volumes:
            - ./data/:/var/www/html/
            - ./logs/php.log:/var/log/fpm-php.www.log
    composer:
        image: composer:2
        volumes:
            - ./data:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - internal
    mysql_animal_generator:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql_animal_generator
        hostname: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - internal
networks:
    internal:
        driver: bridge